In [1]:
import numpy as np
import polars as pl
import torch

df = pl.read_parquet(
    "../data/magnus_carlsen_games/part_000000000.parquet"
).slice(0, 10)

In [3]:
df.head()

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬──────────────────────┐
│ encoded_board                   ┆ encoded_policy_target           ┆ encoded_value_target │
│ ---                             ┆ ---                             ┆ ---                  │
│ binary                          ┆ binary                          ┆ binary               │
╞═════════════════════════════════╪═════════════════════════════════╪══════════════════════╡
│ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x1e\xa9"          │
│ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x1e)"             │
│ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x1e\xa9"          │
│ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x1e)"             │
│ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x00\x00\x00\x00\x00\x00\x00… ┆ b"\x1e\xa9"          │
└─────────────────────────────────┴─────────────────────────────────┴──────────────────────┘

In [4]:
decoded_df = df.select(
    pl.col("encoded_board")
    .map_elements(
        lambda x: torch.from_numpy(
            np.frombuffer(x, dtype=np.float16).astype(np.float16)
        )
    )
    .alias("decoded_board"),
    pl.col("encoded_policy_target")
    .map_elements(
        lambda x: torch.from_numpy(
            np.frombuffer(x, dtype=np.float16).astype(np.float16)
        )
    )
    .alias("decoded_policy_target"),
    pl.col("encoded_value_target")
    .map_elements(
        lambda x: torch.from_numpy(
            np.frombuffer(x, dtype=np.float16).astype(np.float16)
        )
    )
    .alias("decoded_value_target"),
)

In [5]:
decoded_df.head()

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬──────────────────────┐
│ decoded_board                   ┆ decoded_policy_target           ┆ decoded_value_target │
│ ---                             ┆ ---                             ┆ ---                  │
│ object                          ┆ object                          ┆ object               │
╞═════════════════════════════════╪═════════════════════════════════╪══════════════════════╡
│ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([-0.0400],    │
│                                 ┆                                 ┆ dtype=torch.…        │
│ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([0.0400],     │
│                                 ┆                                 ┆ dtype=torch.f…       │
│ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([-0.0400],    │
│                                 ┆                                 ┆ dtype=torch.…        │
│ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([0.0400],     │
│                                 ┆                                 ┆ dtype=torch.f…       │
│ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([0., 0., 0.,  ..., 0., … ┆ tensor([-0.0400],    │
│                                 ┆                                 ┆ dtype=torch.…        │
└─────────────────────────────────┴─────────────────────────────────┴──────────────────────┘